### ISSUE TITLE
Update repo description with current platform support

### ISSUE THREAD

**Issue by whereswaldon** [Inkeliz/giohyperlink#11]
The repo description is:

> Brings the &lt;a href&gt; to Gio. Small library to open URLs, supporting Android, Windows and Linux 

But I'm fairly sure this supports macOS and others. :D

**Comment by inkeliz** [comment]
I change the description, to include iOS/macOS/WASM and FreeBSD.

**Comment by whereswaldon** [comment]
Thank you!
